{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jfrog-credential-provider.fullname" . }}
  namespace: {{ include "jfrog-credential-provider.namespace" . }}
  labels:
    {{- include "jfrog-credential-provider.labels" . | nindent 4 }}
rules:
  {{- range .Values.rbac.role.rules }}
  - {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

