{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jfrog-credential-provider.serviceAccountName" . }}
  namespace: {{ include "jfrog-credential-provider.namespace" . }}
  labels:
    {{- include "jfrog-credential-provider.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

