apiVersion: v2
name: jfrog-credential-provider
description: A Helm chart for JFrog Credential Provider supporting AWS, Azure, and GCP
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - jfrog
  - credential-provider
  - kubernetes
  - aws
  - azure
  - gcp
maintainers:
  - name: JFrog
dependencies:
  - name: jfrog-common
    repository: https://charts.jfrog.io/
    version: 0.0.8

